---
version: '3.7'
services:

  neo4j-core1:
    image: neo4j:4.0.0-enterprise
    container_name: neo4j-core1
    networks:
    - lan
    ports:
    - 7474:7474
    - 6477:6477
    - 7687:7687
    volumes:
    - $PWD/.neo4j/neo4j-core1/conf:/conf
    - $PWD/.neo4j/neo4j-core1/plugins:/plugins
    - $PWD/.neo4j/custom:/custom
    - core1-data:/data
    - core1-logs:/logs
    environment:
    # - NEO4J_AUTH=none
    - NEO4J_AUTH=neo4j/changeme
    - NEO4J_dbms_mode=CORE
    - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    - NEO4J_causal__clustering_minimum__core__cluster__size__at__formation=3
    - NEO4J_causal__clustering_minimum__core__cluster__size__at__runtime=3
    - NEO4J_causal__clustering_initial__discovery__members=neo4j-core1:5000,neo4j-core2:5000,neo4j-core3:5000
    - NEO4J_dbms_connector_http_listen__address=:7474
    - NEO4J_dbms_connector_https_listen__address=:6477
    - NEO4J_dbms_connector_bolt_listen__address=:7687
    - NEO4J_apoc_export_file_enabled=true
    - NEO4J_apoc_import_file_enabled=true
    - NEO4J_apoc_import_file_use__neo4j__config=false
    - NEO4J_dbms_security_procedures_unrestricted=apoc.\\\*

  neo4j-core2:
    image: neo4j:4.0.0-enterprise
    container_name: neo4j-core2
    networks:
    - lan
    ports:
    - 7475:7475
    - 6478:6478
    - 7688:7688
    volumes:
    - $PWD/.neo4j/neo4j-core2/conf:/conf
    - $PWD/.neo4j/neo4j-core1/plugins:/plugins
    - $PWD/.neo4j/custom:/custom
    - core2-data:/data
    - core2-logs:/logs
    environment:
    - NEO4J_AUTH=neo4j/changeme
    - NEO4J_dbms_mode=CORE
    - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    - NEO4J_causal__clustering_minimum__core__cluster__size__at__formation=3
    - NEO4J_causal__clustering_minimum__core__cluster__size__at__runtime=3
    - NEO4J_causal__clustering_initial__discovery__members=neo4j-core1:5000,neo4j-core2:5000,neo4j-core3:5000
    - NEO4J_dbms_connector_http_listen__address=:7475
    - NEO4J_dbms_connector_https_listen__address=:6478
    - NEO4J_dbms_connector_bolt_listen__address=:7688
    - NEO4J_apoc_export_file_enabled=true
    - NEO4J_apoc_import_file_enabled=true
    - NEO4J_apoc_import_file_use__neo4j__config=false
    - NEO4J_dbms_security_procedures_unrestricted=apoc.\\\*

  neo4j-core3:
    image: neo4j:4.0.0-enterprise
    container_name: neo4j-core3
    networks:
    - lan
    ports:
    - 7476:7476
    - 6479:6479
    - 7689:7689
    volumes:
    - $PWD/.neo4j/neo4j-core3/conf:/conf
    - $PWD/.neo4j/neo4j-core1/plugins:/plugins
    - $PWD/.neo4j/custom:/custom
    - core3-data:/data
    - core3-logs:/logs
    environment:
    - NEO4J_AUTH=neo4j/changeme
    - NEO4J_dbms_mode=CORE
    - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    - NEO4J_causal__clustering_minimum__core__cluster__size__at__formation=3
    - NEO4J_causal__clustering_minimum__core__cluster__size__at__runtime=3
    - NEO4J_causal__clustering_initial__discovery__members=neo4j-core1:5000,neo4j-core2:5000,neo4j-core3:5000
    - NEO4J_dbms_connector_http_listen__address=:7476
    - NEO4J_dbms_connector_https_listen__address=:6479
    - NEO4J_dbms_connector_bolt_listen__address=:7689
    - NEO4J_apoc_export_file_enabled=true
    - NEO4J_apoc_import_file_enabled=true
    - NEO4J_apoc_import_file_use__neo4j__config=false
    - NEO4J_dbms_security_procedures_unrestricted=apoc.\\\*

  # This core demonstrates that additional instances can be added after the initial core is established 
  # (ie: this instance is nost listed within "initialDiscoveryMembers")
  neo4j-core4:
    image: neo4j:4.0.0-enterprise
    container_name: neo4j-core4
    networks:
    - lan
    ports:
    - 7478:7478
    - 6481:6481
    - 7691:7691
    volumes:
    - $PWD/.neo4j/neo4j-core4/conf:/conf
    - $PWD/.neo4j/neo4j-core1/plugins:/plugins
    - $PWD/.neo4j/custom:/custom
    - core4-data:/data
    - core4-logs:/logs
    environment:
    - NEO4J_AUTH=neo4j/changeme
    - NEO4J_dbms_mode=CORE
    - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    # - NEO4J_causalClustering_expectedCoreClusterSize=3
    - NEO4J_causal__clustering_initial__discovery__members=core1:5000,core2:5000,core3:5000
    - NEO4J_dbms_connector_http_listen__address=:7478
    - NEO4J_dbms_connector_https_listen__address=:6481
    - NEO4J_dbms_connector_bolt_listen__address=:7691
    - NEO4J_apoc_export_file_enabled=true
    - NEO4J_apoc_import_file_enabled=true
    - NEO4J_apoc_import_file_use__neo4j__config=false
    - NEO4J_dbms_security_procedures_unrestricted=apoc.\\\*

  neo4j-read1:
    image: neo4j:4.0.0-enterprise
    container_name: neo4j-read1
    networks:
    - lan
    ports:
    - 7477:7477
    - 6480:6480
    - 7690:7690
    volumes:
    - $PWD/.neo4j/neo4j-read1/conf:/conf
    - $PWD/.neo4j/neo4j-core1/plugins:/plugins
    - $PWD/.neo4j/custom:/custom
    - read1-data:/data
    - read1-logs:/logs
    environment:
    - NEO4J_AUTH=neo4j/changeme
    - NEO4J_dbms_mode=READ_REPLICA
    - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    - NEO4J_causalClustering_initialDiscoveryMembers=neo4j-core1:5000,neo4j-core2:5000,neo4j-core3:5000
    - NEO4J_dbms_connector_http_listen__address=:7477
    - NEO4J_dbms_connector_https_listen__address=:6480
    - NEO4J_dbms_connector_bolt_listen__address=:7690
    - NEO4J_apoc_export_file_enabled=true
    - NEO4J_apoc_import_file_enabled=true
    - NEO4J_apoc_import_file_use__neo4j__config=false
    - NEO4J_dbms_security_procedures_unrestricted=apoc.\\\*

volumes:
  core1-data:
  core2-data:
  core3-data:
  core4-data:
  read1-data:
  core1-logs:
  core2-logs:
  core3-logs:
  core4-logs:
  read1-logs:

networks:
  lan:
