after_script:
  - docker images

before_script:
  - cd dockerfiles/"$VERSION"
  - IMAGE="x0rzkov/twint:${VERSION/\//-}"

env:
  - VERSION=latest
  - VERSION=latest/alpine

language: bash

script:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker build -t "$IMAGE" .
  - docker push "$IMAGE"

services: docker
