after_script:
  - docker images

before_script:
  - cd dockerfiles/"$VERSION"
  - IMAGE="x0rzkov/twint:${VERSION/\//-}"

env:
  - VERSION=2.0.0
  - VERSION=2.0.0/alpine
  - VERSION=2.1.8
  - VERSION=2.1.8/alpine
  - VERSION=2.1.4
  - VERSION=2.1.4/alpine
  - VERSION=2.1.6
  - VERSION=2.1.6/alpine
  - VERSION=1.1.2.1
  - VERSION=1.1.2.1/alpine
  - VERSION=2.1.9
  - VERSION=2.1.9/alpine
  - VERSION=1.1.3
  - VERSION=1.1.3/alpine
  - VERSION=1.1.2
  - VERSION=1.1.2/alpine
  - VERSION=2.1.10
  - VERSION=2.1.10/alpine
  - VERSION=2.1.0
  - VERSION=2.1.0/alpine
  - VERSION=1.1.3.1
  - VERSION=1.1.3.1/alpine
  - VERSION=latest
  - VERSION=latest/alpine

language: bash

script:
  - docker build -t "$IMAGE" .
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker push "$IMAGE"

services: docker