after_script:
  - docker images

before_script:
  - cd dockerfiles/"$VERSION"
  - IMAGE="x0rzkov/twint:${VERSION/\//-}"

before_install:
  - sudo rm -f /usr/local/bin/docker-slim
  - sudo rm -f /usr/local/bin/docker-slim-sensor
  - curl -L https://github.com/docker-slim/docker-slim/releases/download/1.26.1/dist_linux.tar.gz --output docker-slim.tar.gz
  - tar xvf docker-slim.tar.gz
  - chmod +x dist_linux/docker-slim
  - chmod +x dist_linux/docker-slim-sensor
  - sudo mv dist_linux/docker-slim /usr/local/bin
  - sudo mv dist_linux/docker-slim-sensor /usr/local/bin

env:
  - VERSION=2.1.9
  - VERSION=2.1.9/alpine
  - VERSION=2.0.0
  - VERSION=2.0.0/alpine
  - VERSION=1.1.2
  - VERSION=1.1.2/alpine
  - VERSION=2.1.10
  - VERSION=2.1.10/alpine
  - VERSION=2.1.6
  - VERSION=2.1.6/alpine
  - VERSION=2.1.0
  - VERSION=2.1.0/alpine
  - VERSION=1.1.3
  - VERSION=1.1.3/alpine
  - VERSION=1.1.2.1
  - VERSION=1.1.2.1/alpine
  - VERSION=2.1.4
  - VERSION=2.1.4/alpine
  - VERSION=1.1.3.1
  - VERSION=1.1.3.1/alpine
  - VERSION=2.1.8
  - VERSION=2.1.8/alpine
  - VERSION=latest
  - VERSION=latest/alpine

language: bash

script:
  - docker-slim version
  - docker build -t "$IMAGE" .
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker push "$IMAGE"

services: docker