after_script:
  - docker images

sudo: required

before_install:
  - sudo rm -f /usr/local/bin/docker-slim
  - sudo rm -f /usr/local/bin/docker-slim-sensor
  - curl -L https://github.com/docker-slim/docker-slim/releases/download/1.26.1/dist_linux.tar.gz --output docker-slim.tar.gz
  - tar xvf docker-slim.tar.gz
  - chmod +x dist_linux/docker-slim
  - chmod +x dist_linux/docker-slim-sensor
  - sudo mv dist_linux/docker-slim /usr/local/bin
  - sudo mv dist_linux/docker-slim-sensor /usr/local/bin
  - echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
  - sudo service docker restart
  - docker-compose --version
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/1.25.0/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose --version
  - docker ps

before_script:
  - cd dockerfiles/"$VERSION"
  - IMAGE="x0rzkov/twint:${VERSION/\//-}"

env:
  - VERSION=2.1.10
  - VERSION=2.1.10/alpine
  - VERSION=2.1.10/slim
  - VERSION=2.1.11
  - VERSION=2.1.11/alpine
  - VERSION=2.1.11/slim
  - VERSION=2.1.4
  - VERSION=2.1.4/alpine
  - VERSION=2.1.4/slim
  - VERSION=2.1.8
  - VERSION=2.1.8/alpine
  - VERSION=2.1.8/slim
  - VERSION=2.1.9
  - VERSION=2.1.9/alpine
  - VERSION=2.1.9/slim
  - VERSION=2.1.6
  - VERSION=2.1.6/alpine
  - VERSION=2.1.6/slim
  - VERSION=2.1.0
  - VERSION=2.1.0/alpine
  - VERSION=2.1.0/slim
  - VERSION=2.0.0
  - VERSION=2.0.0/alpine
  - VERSION=2.0.0/slim
  - VERSION=latest
  - VERSION=latest/alpine
  - VERSION=latest/slim

language: bash

script:
  - docker-slim version
  - docker build --squash -t "$IMAGE" .
  - sudo docker-slim build "$IMAGE"
  - sudo docker run -ti "$IMAGE" -h
  - docker network create nw-twint
  - docker-compose up -d
  - docker images
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push "$IMAGE"

services: docker