# refs.
# - https://jjasghar.github.io/blog/2018/11/14/using-travis-ci-deploying-docker-container-to-the-public-docker-registry/
# - https://docs.travis-ci.com/user/docker/
# - https://docs.travis-ci.com/user/environment-variables/#encrypting-environment-variables

travis encrypt --pro DOCKER_USERNAME="x0rzkov"
travis encrypt --pro DOCKER_USERNAME="ada33ve79T!"
travis env --pro set DOCKER_USERNAME x0rzkov
travis env --pro set DOCKER_PASSWORD ada33ve79T!

after_script:
  - docker images

before_script:
  - cd dockerfiles/"$VERSION"
  - IMAGE="x0rzkov/twint:${VERSION/\//-}"

env:
  - VERSION=latest
  - VERSION=latest/alpine

language: bash

script:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker build -t "$IMAGE" .
  - docker push "$IMAGE"

services: docker
