---
version: '3.7'
services:

  twint:
    build:
      context: dockerfiles/latest/alpine
      dockerfile: Dockerfile
    container_name: twint
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${KIBANA_VERSION}
    container_name: twint_elastic
    environment:
    - node.name=elasticsearch
    - cluster.initial_master_nodes=elasticsearch
    - cluster.name=docker-cluster
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=${ELASTIC_JAVA_OPTS}"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
    - esdata01:/usr/share/elasticsearch/data
    ports:
    - 9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:${KIBANA_VERSION}
    container_name: twint_kibana
    ports:
    - 5601:5601

volumes:
  esdata01:
    driver: local

networks:
  default:
    external:
      name: nw_twint