---
version: '3.7'
services:

  twint:
    image: x0rzkov/twint:latest-slim
    build:
      context: .
      dockerfile: Dockerfile
    container_name: twint-cli

  twint-search:
    image: x0rzkov/twint-search:latest
    container_name: twint-search
    ports:
    - 3000:3000
    environment:
    - NODE_ENV=production

  tor-privoxy:
    container_name: twint_torprivoxy
    image: dockage/tor-privoxy:latest
    ports:
    - "9050:9050" # Tor proxy
    - "9051:9051" # Tor control port
    - "8118:8118" # Privoxy  

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.1
    container_name: twint_elastic
    environment:
    - node.name=elasticsearch
    - cluster.initial_master_nodes=elasticsearch
    - cluster.name=docker-cluster
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
    - esdata01:/usr/share/elasticsearch/data
    ports:
    - 9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:7.0.1
    container_name: twint_kibana
    ports:
    - 5601:5601

volumes:
  esdata01:
    driver: local

networks:
  default:
    external:
      name: nw_twint